config/routes.rb
Rails.application.routes.draw do
  


  root 'static_pages#home'
  get '/help'=>'static_pages#help'
  get '/about'=>'static_pages#about'
  get '/contact'=> 'static_pages#contact'
  
  #get 'posts/index'=>'posts#index'
  #get 'posts/new'=>'posts#new'
  post'posts/create'=>'posts#create' ,as: 'posts'
  delete 'posts/destoy'=>'posts#destroy',as: 'post_destroy'
  # 'posts/:user_id/edit' => 'posts#edit',as: 'edit_posts'
  #patch'posts/:user_id/update'=>'posts#update'
  #get 'posts/:user_id'=>'posts#show',as: 'posts'
  
  get '/users'=>'users#index',as: 'users_index'
  get '/users/new'=>'users#new',as: 'users_new'
  post'/users/new'=>'users#create',as: 'signup_create'
  get '/users/:id/following'=>'users#following',as: 'following_user'
  get '/users/:id/followers'=>'users#followers',as: 'followers_user'
  get 'users/:id/edit'=>'users#edit',as: 'edit_user'
  get'users/show_follow'=>'users#show_follow',as: 'show_follow'
  patch 'users/:id'=>'users#update',as: 'users'
  delete 'users/:id'=>'users#destroy',as: 'user_destroy'
  get 'users/:id'=>'users#show',as: 'user'
     

  get 'account_activations/:id/edit'=>'account_activations#edit',as: 'edit_account_activation'
  get 'password_resets/new'=> 'password_resets#new',as: 'new_password_reset'
  post 'password_resets/create'=>'password_resets#create',as: 'password_resets'
  get 'password_resets/:id/edit'=>'password_resets#edit',as: 'edit_password_reset'
  patch'password_resets/:id/update'=>'password_resets#update',as: 'password_reset'
  
  
  get '/login'=>'sessions#new',as: 'login'
  delete'/logout'=>'sessions#destroy'
  post '/login'=>'sessions#create',as: 'login_create'
  
 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token, :activation_token, :reset_token #attr_accessorを使ってアクセス可能な属性を作成する。
    has_secure_password
    has_many :posts, dependent: :destroy
    has_many :relationships, foreign_key: "follower_id", dependent: :destroy
 
 
    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                    dependent:   :destroy
    has_many :active_relationships,  class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy                                 
    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower
  
    before_save   :downcase_email
    before_create :create_activation_digest

    validates :username, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                 format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
   # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
          digest = self.send("#{attribute}_digest")
          return false if digest.nil?
          BCrypt::Password.new(digest).is_password?(token)
  end
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) 
                OR user_id = :user_id", user_id: id)
  end

  def activate
    update_attribute(:activated,  true)
    update_attribute(:activated_at, Time.zone.now)
  end
  # 有効化用のメールを送信する
 
   # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
     #update_attribute(:reset_digest,  User.digest(reset_token))
     #update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
   # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  private
  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :correct_user,   only: [:edit, :update]
    before_action :admin_user,     only: :destroy
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  def index
      @users = User.paginate(page: params[:page])
  end

  def new
    @user=User.new
    #p"==============="
    #p params
    #p"==================new"
  end
  
  def create
    @user=User.new(user_params)
      if @user.save
        @user.send_activation_email#確認メールを送信
        flash[:info] = "Please check your email to activate your account."
        redirect_to root_path
         flash[:email] = "Your message was successfully sent."
         #p"========create======="
         #p params
         #p"=================="
         #p"============"
         #p @user.errors.full_messages
         #p"============"
      else
        flash.now[:error] = 'Invalid email/password combination'
        render 'new'
      end
  end
  
  def show
    @user=User.find_by(id: params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
  
  def update
     #p"============"
        #   p @user.errors.full_messages
      #p"============"
       @user = User.find(params[:id])

      if @user.update_attributes(user_params)
          #  session[:user_id]=user.id
          flash[:success] = "Profile updated"
          redirect_to @user
      else
        render :edit
      end
  end
  
  def edit
      @user=User.find_by(id: params[:id])
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_index_path
  end
   
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  
  private
  def set_user
      @user = User.find(params[:id])     
  end
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end
      # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user 
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
        # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
       redirect_to(root_url) unless current_user?(@user)
    end
     # 管理者かどうかを確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
     # 有効化用のメールを送信する
  
end

app/helpers/users_helper.rb
module UsersHelper
   def gravatar_for(user, options = { size: 80 })
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "gravatar")
   end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%=form_with model: @user ,url: yield(:form_action), local: true  do |f| %>
     <%= render 'shared/error_messages', object: f.object  %>
        signup
        <% if local_assigns[:sign_up].present?%>
          <%= f.label :username %>
          <%= f.text_field :username, class: 'form-control' %>
        <% end %>
       <%#= render 'shared/error_messages' @user%>
       login
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      <% if local_assigns[:sign_up].present?%>
        <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
              <%= f.label :remember_me, class: "checkbox inline" do %>
              <%= f.check_box :remember_me %>
                <span>Remember me on this computer</span>
              <% end %> 
      <% end %>    
        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
    

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/_user.htm.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.username, user %>
   <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/_user.html.erb
<li><%= gravatar_for user, size: 50 %>
  <%= link_to user.username, user_path(current_user.id) %>
   <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user_destroy_path(user), method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<% provide(:title, "Edit user") %>
<% provide(:form_action, users_path(@user) )%>
<div class="container">
    <h1>sign_up page</h1>
      <%= render  "form",:sign_up => true,local:{user: @user }%> 
 <%= hidden_field_tag :email, @user.email %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>ALL users</h1>


<ul class="users">
  <%= render @users %>
</ul>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= will_paginate @users %>
<%# @users.each do |user| %>

<%# end %>
<%#= will_paginate %>
</table>

<br>

<%#= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:form_action, signup_create_path)%>

  
   <div class="container">
    <h1>sign_up page</h1>
      <%= render "form", :sign_up => true, locals: {user: @user}%> 
    </div>
 

app/views/users/show.html.erb
 <p><% provide(:title, @user.username) %></p>
   <div class="row">
    <div>
     <h1><p><%= gravatar_for @user %></p></h1>
     <p><%= @user.username %></p>
     <p> user_email:<%= @user.email%></p>
     <p><%= @user.created_at %>, <%= @user.updated_at %></p>
     <p>Time.now: <%= Time.now %></p>
    </div>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
     <%= render 'follow_form' if logged_in? %>
       <div class="col-md-8">
         <% if @user.posts.any? %>
           <h3>posts (<%= @user.posts.count %>)</h3>
           <% if @posts.present? %>
                <%= render @posts %>
                <%= will_paginate @posts %>
           <% end %>
             </ol>
           </div>
         <% end %>
       </div>

  
 

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.username %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.posts.any? %>
      <h3>posts (<%= @user.posts.count %>)</h3>
      <ol class="microposts">
      <% if @posts.present? %>      
        <%= render @posts %>
     
      </ol>
       <%= will_paginate @posts %>
      <% end %>
    <% end %>
  </div>  
</div>