config/routes.rb
Rails.application.routes.draw do
  


  root 'static_pages#home'
  get '/help'=>'static_pages#help'
  get '/about'=>'static_pages#about'
  get '/contact'=> 'static_pages#contact'
  
  #get 'posts/index'=>'posts#index'
  #get 'posts/new'=>'posts#new'
  post'posts/create'=>'posts#create' ,as: 'posts'
  delete 'posts/destoy'=>'posts#destroy',as: 'post_destroy'
  # 'posts/:user_id/edit' => 'posts#edit',as: 'edit_posts'
  #patch'posts/:user_id/update'=>'posts#update'
  #get 'posts/:user_id'=>'posts#show',as: 'posts'
  
  get '/users'=>'users#index',as: 'users_index'
  get '/users/new'=>'users#new',as: 'users_new'
  post'/users/new'=>'users#create',as: 'signup_create'
  get '/users/:id/following'=>'users#following',as: 'following_user'
  get '/users/:id/followers'=>'users#followers',as: 'followers_user'
  get 'users/:id/edit'=>'users#edit',as: 'edit_user'
  get'users/show_follow'=>'users#show_follow',as: 'show_follow'
  patch 'users/:id'=>'users#update',as: 'users'
  delete 'users/:id'=>'users#destroy',as: 'user_destroy'
  get 'users/:id'=>'users#show',as: 'user'
     

  get 'account_activations/:id/edit'=>'account_activations#edit',as: 'edit_account_activation'
  get 'password_resets/new'=> 'password_resets#new',as: 'new_password_reset'
  post 'password_resets/create'=>'password_resets#create',as: 'password_resets'
  get 'password_resets/:id/edit'=>'password_resets#edit',as: 'edit_password_reset'
  patch'password_resets/:id/update'=>'password_resets#update',as: 'password_reset'
  
  
  get '/login'=>'sessions#new',as: 'login'
  delete'/logout'=>'sessions#destroy'
  post '/login'=>'sessions#create',as: 'login_create'
  
 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.present? && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <div class="posts">
    <p><%= render @feed_items %></p>
  </div>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_navbar.html.erb
<% if logged_in? %>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TEST</a>
      <a class="navbar-brand">現在<%=current_user.username%>様がログイン中</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"> <%= link_to "Home",root_path %></a>
          </li>
           <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"> <%= link_to "Users", users_index_path %></a>
          </li>
        

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"> <%= link_to "mypage",user_path(current_user.id,current_user.posts.ids) %></a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"><%= link_to "Settings", edit_user_path(current_user.id) %></a>
          </li>
          
         <li class="nav-item">
             <%= link_to "logout",logout_path, method: :delete %>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= link_to "Help",  help_path %></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% else %>  
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TEST</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"> <%= link_to "Home",  root_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= link_to "Help",  help_path %></a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               start
            </a>
             <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#"></a></li>
              <li><a class="dropdown-item" href="#">  <%= link_to "sine_up", users_new_path %></a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#"> <%= link_to "login", login_path %></a></li>
            </ul>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_post_form.html.erb
<span><%= pluralize(current_user.posts.count, "post") %></span>
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  
   <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_starts.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.hrml.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", user_path(current_user.id) %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>