config/routes.rb
Rails.application.routes.draw do
  


  root 'static_pages#home'
  get '/help'=>'static_pages#help'
  get '/about'=>'static_pages#about'
  get '/contact'=> 'static_pages#contact'
  
  #get 'posts/index'=>'posts#index'
  #get 'posts/new'=>'posts#new'
  post'posts/create'=>'posts#create' ,as: 'posts'
  delete 'posts/destoy'=>'posts#destroy',as: 'post_destroy'
  # 'posts/:user_id/edit' => 'posts#edit',as: 'edit_posts'
  #patch'posts/:user_id/update'=>'posts#update'
  #get 'posts/:user_id'=>'posts#show',as: 'posts'
  
  get '/users'=>'users#index',as: 'users_index'
  get '/users/new'=>'users#new',as: 'users_new'
  post'/users/new'=>'users#create',as: 'signup_create'
  get '/users/:id/following'=>'users#following',as: 'following_user'
  get '/users/:id/followers'=>'users#followers',as: 'followers_user'
  get 'users/:id/edit'=>'users#edit',as: 'edit_user'
  get'users/show_follow'=>'users#show_follow',as: 'show_follow'
  patch 'users/:id'=>'users#update',as: 'users'
  delete 'users/:id'=>'users#destroy',as: 'user_destroy'
  get 'users/:id'=>'users#show',as: 'user'
     

  get 'account_activations/:id/edit'=>'account_activations#edit',as: 'edit_account_activation'
  get 'password_resets/new'=> 'password_resets#new',as: 'new_password_reset'
  post 'password_resets/create'=>'password_resets#create',as: 'password_resets'
  get 'password_resets/:id/edit'=>'password_resets#edit',as: 'edit_password_reset'
  patch'password_resets/:id/update'=>'password_resets#update',as: 'password_reset'
  
  
  get '/login'=>'sessions#new',as: 'login'
  delete'/logout'=>'sessions#destroy'
  post '/login'=>'sessions#create',as: 'login_create'
  
 
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <hr size="6"></hr>
  <footer class="footer">
    <div class="footer_left">
    <small>
      The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    </div>
    <nav>
    <div class="detail"> 
        <p><%= link_to "About",    about_path %>
        <%= link_to "Contact",  contact_path %>
        <a href="http://news.railstutorial.org/">News</a></p>

    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_index_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user.id) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_url, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_url %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
  </head>
  <body>
  <%= render 'layouts/header' %>
    <%= render partial: "shared/navbar"  %>
    <%= yield :form_action %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
     <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>